### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by nimamanisha** [polimi-ispl/cnn-fast-sdi#1]
Hi,

Can you please provide the source code?

Thank you.

**Comment by smandelli** [comment]
Hi,
sorry for the delay. I will provide the code asap and let you know

**Comment by nimamanisha** [comment]
Thank you very much.

**Comment by smandelli** [comment]
Hi, 
I uploaded the code and I'm closing the issue.

**Comment by nimamanisha** [comment]
Hi,

Thank you very much. It was a great help.

Regards
Manisha
