### ISSUE TITLE
input image npy file generation

### ISSUE THREAD

**Issue by nimamanisha** [polimi-ispl/cnn-fast-sdi#2]
Hi,

Would you please share details on how the .npy files are created for training, validation, and evaluation images along with the class label?

I am getting errors while training the model due to the incorrect .npy file creation.

Would you please help me out in this regard?

Thank you.

Kind regards,
Manisha

**Comment by smandelli** [comment]
Hi @nimamanisha, 
I guess you are referring to the lists containing the paths to noise residuals of images for training, validation and evaluation as reported [here](https://github.com/polimi-ispl/cnn-fast-sdi#extract-image-noise-residuals-and-device-prnu-and-save-them).
It is enough that you extract the noise residual for each image, save them and split the noise residuals of each device in three separated sets (train, val, test). Then, for each camera, create 3 .npy files containing the paths to training/validation/test noise residuals. 
I attach an example of .npy file containing the list of training noise residuals of Canon_Ixus55_0. 
Let me know for any issue.

[list_Canon_Ixus55_0.npy.zip](https://github.com/polimi-ispl/cnn-fast-sdi/files/6432996/list_Canon_Ixus55_0.npy.zip)

**Comment by nimamanisha** [comment]
Hi,

Thank you very much for the detailed explanation. I will check it out and will get back to you if I face any issues.
